version: '3.3'

services:
  # =================================================
  # Our golang app
  # =================================================
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    networks:
      - shared-network
    environment:
      - KEYCLOAK_CLIENT_ID=public
      - KEYCLOAK_CLIENT_SECRET=HXUlT5wMzZTdRkHoLRg1KBsqop2d3ujv
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_URL=http://keycloak:8080
      - DATABASE_URL="host=database user=postgres password=postgres dbname=app port=5432 sslmode=disabled TimeZone=UTC"
    depends_on:
      - keycloak
      - postgress
    
  # =================================================
  # Our keycloak service to authenticate users
  # =================================================
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.2
    command:
      - start-dev 
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8081:8080
    networks: 
      - shared-network

  # =================================================
  # Our sql database
  # =================================================
  postgress:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - 5432:5432
    networks:
      - shared-network

networks:
  shared-network:
    driver: overlay
    attachable: true

volumes:
  db-volume: