# create a docker-compose where we create a keycloak container
# with command start-dev

version: '3.3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command:
      - start-dev 
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8081:8080
    networks: 
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge